name: deploy-documentation

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    # Only run if edits in documentation
    paths:
    - documentation/**
    - .github/workflows/deploy.yml

# This job installs dependencies, builds the book, and pushes it to branch `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install jupyter-book

    # Create "complete_datasets.md" from README.md
    - name: Create complete_datasets.md
      run: |
        python documentation/add_README_to_docs.py

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build documentation/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/_build/html
